### ISSUE TITLE
irtriport_blaster not supported

### ISSUE THREAD

**Issue by kalimsaliba** [dustindclark/homebridge-globalcache-itach#6]
Hi,

Do you have any plans to release a version of this that supports the itach irtriport_blaster?

Thank you.

[8/14/2016, 5:18:30 PM] Loading 1 platforms...
[8/14/2016, 5:18:30 PM] [Global Cache Itach] Initializing GlobalCacheItach platform...
[8/14/2016, 5:18:31 PM] [Global Cache Itach] Connected to 192.168.1.78:48584.  Sending command: getdevices
endlistdevicesRIPORT_BLASTERbal Cache Itach] DATA: device,0,0 WIFI
[8/14/2016, 5:18:31 PM] [Global Cache Itach] Found 1 irtriport_blaster ports.
[8/14/2016, 5:18:31 PM] [Global Cache Itach] Configuring iTach accessory.  Name: Gate - 1, Type: irtriport_blaster at port: 0
/usr/lib/node_modules/homebridge-globalcache-itach/index.js:186
        throw new Error("Unsupported device type: " + this.deviceType);
        ^

Error: Unsupported device type: irtriport_blaster
    at new ItachAccessory (/usr/lib/node_modules/homebridge-globalcache-itach/index.js:186:15)
    at ItachPlatform.<anonymous> (/usr/lib/node_modules/homebridge-globalcache-itach/index.js:94:46)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-globalcache-itach/index.js:314:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

**Comment by elvisguillen** [comment]
I am really curious about irtriport_blaster support as well. I am able to connect to my iTach Flex but I receive the same Unsupported device type error. Let us know, Thanks!

**Comment by dustindclark** [comment]
May be able to revisit soon based on comments in #10. Plugin has been neglected and needs an overhaul in general.
