### ISSUE TITLE
Itach won't start

### ISSUE THREAD

**Issue by wildechild55** [dustindclark/homebridge-globalcache-itach#7]
I try to initialize home bridge with the itach plugin and I get the following error, any ideas?
Thanks in advance

[9/26/2016, 4:31:07 AM] [Global Cache Itach] Initializing GlobalCacheItach platform...
[9/26/2016, 4:31:07 AM] [Global Cache Itach] Connected to 192.168.1.13:38532.  Sending command: getdevices
[9/26/2016, 4:31:07 AM] [Global Cache Itach] Connected to 192.168.1.13:38534.  Sending command: get_IRL
[9/26/2016, 4:31:07 AM] [Global Cache Itach] Connected to 192.168.1.13:38536.  Sending command: getdevices
endlistdevices31:07 AM] [Global Cache Itach] DATA: device,0,0 ETHERNET
[9/26/2016, 4:31:07 AM] [Global Cache Itach] Found 3 ir ports.
[9/26/2016, 4:31:07 AM] [Global Cache Itach] Configuring iTach accessory.  Name: Gate - 1, Type: ir at port: 0
/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:172
        for (var i = 0; i < Object.keys(this.commands).length; i++) {
                                   ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at new ItachAccessory (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:172:36)
    at ItachPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:94:46)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:314:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by wildechild55** [comment]
Will this plugin work with Globalcache IP2IR?

**Comment by wildechild55** [comment]
Got the Issue resolved thanks!

**Comment by geofbuck** [comment]
How did you fix this? I am a noob so please explain in simple terms, preferrably with hand gestures..... I copied the code from the README but it crashes home bridge every time I insert it.

[1/22/2017, 12:49:26 PM] [Global Cache Itach] Connected to 192.168.5.211:60074.  Sending command: getdevices
[1/22/2017, 12:49:26 PM] [Global Cache Itach] Connected to 192.168.5.211:60075.  Sending command: get_IRL
[1/22/2017, 12:49:26 PM] [Global Cache Itach] Connected to 192.168.5.211:60076.  Sending command: getdevices
[1/22/2017, 12:49:26 PM] [My Home] Indigo request: http://127.0.0.1:8176/devices.json/
endlistdevices:49:26 PM] [Global Cache Itach] DATA: device,0,0 ETHERNET
[1/22/2017, 12:49:26 PM] [Global Cache Itach] Found 3 ir ports.
[1/22/2017, 12:49:26 PM] [Global Cache Itach] Configuring iTach accessory.  Name: Office - 1, Type: ir at port: 0
/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:172
        for (var i = 0; i < Object.keys(this.commands).length; i++) {
                                   ^

TypeError: Cannot convert undefined or null to object
    at new ItachAccessory (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:172:36)
    at ItachPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:94:46)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:314:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by alexeyshulzhenko** [comment]
@wildechild55 @geofbuck how did you fix that? the same trouble

**Comment by geofbuck** [comment]
I did fix it finally but I am not at home, but if I remember it had to do with changing the settings for the itach in its web gui. You must set it to have 1 port as a learner port or it won't recognize correctly. I did this and input strings to fire up my office TV and it worked perfectly. The steps for the plug-in are rather crude though, and I had to do much facking around to get the IR code structure correct. If you need more info on that let me know.
