### ISSUE TITLE
Homebridge won't start

### ISSUE THREAD

**Issue by johnmales** [dustindclark/homebridge-globalcache-itach#9]
Hi,
Thanks very much for your great work. I'm having trouble getting homebridge to start once I install the plugin:
```
[10/7/2018, 8:40:37 PM] Loaded config.json with 0 accessories and 1 platforms.
[10/7/2018, 8:40:37 PM] ---
[10/7/2018, 8:40:37 PM] Loaded plugin: homebridge-globalcache-itach
[10/7/2018, 8:40:37 PM] Registering platform 'homebridge-globalcache-itach.GlobalCacheItach'
[10/7/2018, 8:40:37 PM] ---
[10/7/2018, 8:40:37 PM] Loading 1 platforms...
[10/7/2018, 8:40:37 PM] [Global Cache Itach] Initializing GlobalCacheItach platform...
[10/7/2018, 8:40:37 PM] Loading 0 accessories...
[10/7/2018, 8:40:37 PM] [Global Cache Itach] Connected to 192.168.0.96:51880.  Sending command: getdevices
endlistdevices40:37 PM] [Global Cache Itach] DATA: device,0,0 ETHERNET
[10/7/2018, 8:40:37 PM] [Global Cache Itach] Found 3 ir ports.
[10/7/2018, 8:40:37 PM] [Global Cache Itach] Configuring iTach accessory.  Name: Gate - 1, Type: ir at port: 0
/usr/lib/node_modules/homebridge-globalcache-itach/index.js:172
        for (var i = 0; i < Object.keys(this.commands).length; i++) {
                                   ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at new ItachAccessory (/usr/lib/node_modules/homebridge-globalcache-itach/index.js:172:36)
    at ItachPlatform.<anonymous> (/usr/lib/node_modules/homebridge-globalcache-itach/index.js:94:46)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-globalcache-itach/index.js:314:9)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

This seems to be similar to the issue raised in #7 . I haven't been able to find a solution, including changing itach settings in the web gui for the IP2IR.

Any thoughts appreciated! Thanks again.

**Comment by cjastennett** [comment]
Great plugin - but I am having a similar problem - when the iTach device cannot be found on homebridge it will continually crash homebridge and result in a continuous loop of Homebridge re-starts. Any ideas?

**Comment by dustindclark** [comment]
Closing this out since it's super old. May be able to revisit soon based on comments in #10. Reopen if this is still an issue.
